allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
shamefullyHoist: true

overrides:
  "@nuxtjs/tailwindcss": "6.12.2-20241014-164133-9d42549"
  h3: "1.x"

